services:
  ai-metaphors-test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./animations:/app/animations
      - ./config:/app/config
    entrypoint:
      python -m unittest discover -s tests
    env_file:
      - .env
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app