services:
  ai-metaphors:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./animations:/app/animations
      - ./config:/app/config
    entrypoint:
      python -m ai_metaphors.main --bin-directory /usr/local/bin --config config/config.yaml
    env_file:
      - .env
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
