containerPort: 8898
health:
  path: /healthz
ingress:
  enabled: false
runAsUser: 1001
runAsGroup: 1001

resources:
  requests:
    cpu: 1
    memory: 4Gi
    ephemeral-storage: 4Gi
    nvidia.com/gpu: 1
  limits:
    cpu: 2
    memory: 12Gi
    ephemeral-storage: 5Gi
    nvidia.com/gpu: 1

deployStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 0

customEnv:
  - name: OPENAI_API_KEY
    valueFrom:
      secretKeyRef:
        name: metaphors-llm-secret
        key: openai-api-key
  - name: GRAZIE_JWT_TOKEN
    valueFrom:
      secretKeyRef:
        name: metaphors-llm-secret
        key: grazie-jwt-token
  - name: GRAZIE_AUTH_TYPE
    valueFrom:
      secretKeyRef:
        name: metaphors-llm-secret
        key: grazie-auth-type
  - name: POSTGRES_USER
    valueFrom:
      secretKeyRef:
        name: ai-metaphors
        key: username
  - name: POSTGRES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: ai-metaphors
        key: password
  - name: POSTGRES_HOST
    valueFrom:
      secretKeyRef:
        name: ai-metaphors
        key: host
  - name: POSTGRES_PORT
    valueFrom:
      secretKeyRef:
        name: ai-metaphors
        key: port
  - name: POSTGRES_DB
    valueFrom:
      secretKeyRef:
        name: ai-metaphors
        key: name
  - name: BUCKET_NAME
    valueFrom:
      secretKeyRef:
        name: gcs-metaphors
        key: BUCKET_NAME
  - name: KEY_JSON
    valueFrom:
      secretKeyRef:
        name: gcs-metaphors
        key: KEY_JSON
