"""Sync with actual models

Revision ID: 29fb5d45a48c
Revises: 1017db4d6465
Create Date: 2026-02-11 12:06:40.764021

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '29fb5d45a48c'
down_revision: Union[str, Sequence[str], None] = '1017db4d6465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
