"""Add is_admin to users

Revision ID: 3f913564ee79
Revises: 29fb5d45a48c
Create Date: 2026-02-12 02:14:22.779782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f913564ee79'
down_revision: Union[str, Sequence[str], None] = '29fb5d45a48c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add column as nullable
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    
    # 2. Set default value for existing rows
    op.execute("UPDATE users SET is_admin = FALSE")
    
    # 3. Alter column to be NOT NULL
    op.alter_column('users', 'is_admin', nullable=False)
    
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
