"""Add manim_code to video_task

Revision ID: b14831acc358
Revises: cc25e7aacfa6
Create Date: 2026-02-13 09:51:38.100425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b14831acc358'
down_revision: Union[str, Sequence[str], None] = 'cc25e7aacfa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_task', sa.Column('manim_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_task', 'manim_code')
    # ### end Alembic commands ###
