"""Remove api_key from video_task

Revision ID: cc25e7aacfa6
Revises: 3f913564ee79
Create Date: 2026-02-13 08:46:08.523196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc25e7aacfa6'
down_revision: Union[str, Sequence[str], None] = '3f913564ee79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_task_api_key'), table_name='video_task')
    op.drop_column('video_task', 'api_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_task', sa.Column('api_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_video_task_api_key'), 'video_task', ['api_key'], unique=False)
    # ### end Alembic commands ###
