name: Python build

on: [push]

env:
  JETBRAINS_MONO_VERSION: 2.304
  PYTHON_VERSION: "3.10"

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

#      This steps will be re-added on Space
#      - name: Install system dependencies
#        run: |
#          sudo apt-get update
#          sudo apt-get install -y \
#            libpango1.0-dev \
#            libcairo2-dev \
#            pkg-config
#
#      - name: Install Poetry
#        run: |
#          curl -sSL https://install.python-poetry.org | python3 -
#          echo "$HOME/.local/bin" >> $GITHUB_PATH
#
#      - name: Install dependencies
#        run: |
#          poetry lock --no-update
#          poetry install

  code-style:
    needs: setup

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Ruff
        run: pip install ruff

      - name: Check the code
        run: |
          ruff check --output-format=github

      - name: Format the code
        run: |
          ruff format --check
